{"name":"error message when try create organization","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [checking...] but found [not available]","trace":"java.lang.AssertionError: expected [checking...] but found [not available]\r\n\tat org.testng.Assert.fail(Assert.java:96)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:776)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:137)\r\n\tat org.testng.Assert.assertEquals(Assert.java:118)\r\n\tat org.testng.Assert.assertEquals(Assert.java:453)\r\n\tat org.testng.Assert.assertEquals(Assert.java:463)\r\n\tat involve.me.Tests.OrganizationSettingsTest.t_02createNewOrganization(OrganizationSettingsTest.java:38)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:583)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:648)\r\n\tat org.testng.TestRunner.run(TestRunner.java:505)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:364)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1137)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1049)\r\n\tat org.testng.TestNG.run(TestNG.java:1017)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)\r\n"},"stage":"finished","description":"check that can't create new organization if name don't valid","steps":[{"name":"enter not available name for organization","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"organizationName","value":"SSS"}],"start":1580074680462,"stop":1580074681096},{"name":"check 'not available' message","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1580074681097,"stop":1580074681411}],"attachments":[],"parameters":[],"start":1580074680461,"stop":1580074681426,"uuid":"0a3ae681-2d57-4e29-b4ca-2bc7ee4af58e","historyId":"65cab324b1805d9b92e2ae61b0ea8763","fullName":"involve.me.Tests.OrganizationSettingsTest.t_02createNewOrganization","labels":[{"name":"package","value":"involve.me.Tests.OrganizationSettingsTest"},{"name":"testClass","value":"involve.me.Tests.OrganizationSettingsTest"},{"name":"testMethod","value":"t_02createNewOrganization"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"involve.me.Tests.OrganizationSettingsTest"},{"name":"host","value":"LAPTOP-4TARQOGN"},{"name":"thread","value":"4324@LAPTOP-4TARQOGN.main(1)"},{"name":"severity","value":"normal"}],"links":[]}